/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminContentRouteImport } from './routes/admin/content'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAtRiskRouteImport } from './routes/dashboard/at-risk'
import { Route as DashboardBrandingRouteImport } from './routes/dashboard/branding'
import { Route as DashboardCustomersRouteImport } from './routes/dashboard/customers'
import { Route as DashboardInviteRouteImport } from './routes/dashboard/invite'
import { Route as DashboardReorderRouteImport } from './routes/dashboard/reorder'
import { Route as DashboardTestimonialsRouteImport } from './routes/dashboard/testimonials'
import { Route as AuthenticatedPTenantSlugRouteImport } from './routes/_authenticated/p.$tenantSlug'
import { Route as DashboardCustomersCustomerIdRouteImport } from './routes/dashboard/customers.$customerId'
import { Route as PTenantSlugJoinRouteImport } from './routes/p/$tenantSlug/join'
import { Route as AuthenticatedPTenantSlugCompleteRouteImport } from './routes/_authenticated/p.$tenantSlug.complete'
import { Route as AuthenticatedPTenantSlugGuideRouteImport } from './routes/_authenticated/p.$tenantSlug.guide'
import { Route as AuthenticatedPTenantSlugJourneyRouteImport } from './routes/_authenticated/p.$tenantSlug.journey'
import { Route as AuthenticatedPTenantSlugKitRouteImport } from './routes/_authenticated/p.$tenantSlug.kit'
import { Route as AuthenticatedPTenantSlugProgressRouteImport } from './routes/_authenticated/p.$tenantSlug.progress'
import { Route as AuthenticatedPTenantSlugTodayRouteImport } from './routes/_authenticated/p.$tenantSlug.today'
import { Route as AdminContentProgramsProgramIdDaysRouteImport } from './routes/admin/content/programs/$programId/days'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAtRiskRoute = DashboardAtRiskRouteImport.update({
  id: '/at-risk',
  path: '/at-risk',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBrandingRoute = DashboardBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCustomersRoute = DashboardCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInviteRoute = DashboardInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReorderRoute = DashboardReorderRouteImport.update({
  id: '/reorder',
  path: '/reorder',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTestimonialsRoute = DashboardTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthenticatedPTenantSlugRoute =
  AuthenticatedPTenantSlugRouteImport.update({
    id: '/p/$tenantSlug',
    path: '/p/$tenantSlug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const DashboardCustomersCustomerIdRoute =
  DashboardCustomersCustomerIdRouteImport.update({
    id: '/$customerId',
    path: '/$customerId',
    getParentRoute: () => DashboardCustomersRoute,
  } as any)
const PTenantSlugJoinRoute = PTenantSlugJoinRouteImport.update({
  id: '/p/$tenantSlug/join',
  path: '/p/$tenantSlug/join',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPTenantSlugCompleteRoute =
  AuthenticatedPTenantSlugCompleteRouteImport.update({
    id: '/complete',
    path: '/complete',
    getParentRoute: () => AuthenticatedPTenantSlugRoute,
  } as any)
const AuthenticatedPTenantSlugGuideRoute =
  AuthenticatedPTenantSlugGuideRouteImport.update({
    id: '/guide',
    path: '/guide',
    getParentRoute: () => AuthenticatedPTenantSlugRoute,
  } as any)
const AuthenticatedPTenantSlugJourneyRoute =
  AuthenticatedPTenantSlugJourneyRouteImport.update({
    id: '/journey',
    path: '/journey',
    getParentRoute: () => AuthenticatedPTenantSlugRoute,
  } as any)
const AuthenticatedPTenantSlugKitRoute =
  AuthenticatedPTenantSlugKitRouteImport.update({
    id: '/kit',
    path: '/kit',
    getParentRoute: () => AuthenticatedPTenantSlugRoute,
  } as any)
const AuthenticatedPTenantSlugProgressRoute =
  AuthenticatedPTenantSlugProgressRouteImport.update({
    id: '/progress',
    path: '/progress',
    getParentRoute: () => AuthenticatedPTenantSlugRoute,
  } as any)
const AuthenticatedPTenantSlugTodayRoute =
  AuthenticatedPTenantSlugTodayRouteImport.update({
    id: '/today',
    path: '/today',
    getParentRoute: () => AuthenticatedPTenantSlugRoute,
  } as any)
const AdminContentProgramsProgramIdDaysRoute =
  AdminContentProgramsProgramIdDaysRouteImport.update({
    id: '/programs/$programId/days',
    path: '/programs/$programId/days',
    getParentRoute: () => AdminContentRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/admin/content': typeof AdminContentRouteWithChildren
  '/dashboard/at-risk': typeof DashboardAtRiskRoute
  '/dashboard/branding': typeof DashboardBrandingRoute
  '/dashboard/customers': typeof DashboardCustomersRouteWithChildren
  '/dashboard/invite': typeof DashboardInviteRoute
  '/dashboard/reorder': typeof DashboardReorderRoute
  '/dashboard/testimonials': typeof DashboardTestimonialsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/p/$tenantSlug': typeof AuthenticatedPTenantSlugRouteWithChildren
  '/dashboard/customers/$customerId': typeof DashboardCustomersCustomerIdRoute
  '/p/$tenantSlug/join': typeof PTenantSlugJoinRoute
  '/p/$tenantSlug/complete': typeof AuthenticatedPTenantSlugCompleteRoute
  '/p/$tenantSlug/guide': typeof AuthenticatedPTenantSlugGuideRoute
  '/p/$tenantSlug/journey': typeof AuthenticatedPTenantSlugJourneyRoute
  '/p/$tenantSlug/kit': typeof AuthenticatedPTenantSlugKitRoute
  '/p/$tenantSlug/progress': typeof AuthenticatedPTenantSlugProgressRoute
  '/p/$tenantSlug/today': typeof AuthenticatedPTenantSlugTodayRoute
  '/admin/content/programs/$programId/days': typeof AdminContentProgramsProgramIdDaysRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/admin/content': typeof AdminContentRouteWithChildren
  '/dashboard/at-risk': typeof DashboardAtRiskRoute
  '/dashboard/branding': typeof DashboardBrandingRoute
  '/dashboard/customers': typeof DashboardCustomersRouteWithChildren
  '/dashboard/invite': typeof DashboardInviteRoute
  '/dashboard/reorder': typeof DashboardReorderRoute
  '/dashboard/testimonials': typeof DashboardTestimonialsRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/p/$tenantSlug': typeof AuthenticatedPTenantSlugRouteWithChildren
  '/dashboard/customers/$customerId': typeof DashboardCustomersCustomerIdRoute
  '/p/$tenantSlug/join': typeof PTenantSlugJoinRoute
  '/p/$tenantSlug/complete': typeof AuthenticatedPTenantSlugCompleteRoute
  '/p/$tenantSlug/guide': typeof AuthenticatedPTenantSlugGuideRoute
  '/p/$tenantSlug/journey': typeof AuthenticatedPTenantSlugJourneyRoute
  '/p/$tenantSlug/kit': typeof AuthenticatedPTenantSlugKitRoute
  '/p/$tenantSlug/progress': typeof AuthenticatedPTenantSlugProgressRoute
  '/p/$tenantSlug/today': typeof AuthenticatedPTenantSlugTodayRoute
  '/admin/content/programs/$programId/days': typeof AdminContentProgramsProgramIdDaysRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/admin/content': typeof AdminContentRouteWithChildren
  '/dashboard/at-risk': typeof DashboardAtRiskRoute
  '/dashboard/branding': typeof DashboardBrandingRoute
  '/dashboard/customers': typeof DashboardCustomersRouteWithChildren
  '/dashboard/invite': typeof DashboardInviteRoute
  '/dashboard/reorder': typeof DashboardReorderRoute
  '/dashboard/testimonials': typeof DashboardTestimonialsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/_authenticated/p/$tenantSlug': typeof AuthenticatedPTenantSlugRouteWithChildren
  '/dashboard/customers/$customerId': typeof DashboardCustomersCustomerIdRoute
  '/p/$tenantSlug/join': typeof PTenantSlugJoinRoute
  '/_authenticated/p/$tenantSlug/complete': typeof AuthenticatedPTenantSlugCompleteRoute
  '/_authenticated/p/$tenantSlug/guide': typeof AuthenticatedPTenantSlugGuideRoute
  '/_authenticated/p/$tenantSlug/journey': typeof AuthenticatedPTenantSlugJourneyRoute
  '/_authenticated/p/$tenantSlug/kit': typeof AuthenticatedPTenantSlugKitRoute
  '/_authenticated/p/$tenantSlug/progress': typeof AuthenticatedPTenantSlugProgressRoute
  '/_authenticated/p/$tenantSlug/today': typeof AuthenticatedPTenantSlugTodayRoute
  '/admin/content/programs/$programId/days': typeof AdminContentProgramsProgramIdDaysRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/admin/content'
    | '/dashboard/at-risk'
    | '/dashboard/branding'
    | '/dashboard/customers'
    | '/dashboard/invite'
    | '/dashboard/reorder'
    | '/dashboard/testimonials'
    | '/admin/'
    | '/dashboard/'
    | '/p/$tenantSlug'
    | '/dashboard/customers/$customerId'
    | '/p/$tenantSlug/join'
    | '/p/$tenantSlug/complete'
    | '/p/$tenantSlug/guide'
    | '/p/$tenantSlug/journey'
    | '/p/$tenantSlug/kit'
    | '/p/$tenantSlug/progress'
    | '/p/$tenantSlug/today'
    | '/admin/content/programs/$programId/days'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/admin/content'
    | '/dashboard/at-risk'
    | '/dashboard/branding'
    | '/dashboard/customers'
    | '/dashboard/invite'
    | '/dashboard/reorder'
    | '/dashboard/testimonials'
    | '/admin'
    | '/dashboard'
    | '/p/$tenantSlug'
    | '/dashboard/customers/$customerId'
    | '/p/$tenantSlug/join'
    | '/p/$tenantSlug/complete'
    | '/p/$tenantSlug/guide'
    | '/p/$tenantSlug/journey'
    | '/p/$tenantSlug/kit'
    | '/p/$tenantSlug/progress'
    | '/p/$tenantSlug/today'
    | '/admin/content/programs/$programId/days'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/admin/content'
    | '/dashboard/at-risk'
    | '/dashboard/branding'
    | '/dashboard/customers'
    | '/dashboard/invite'
    | '/dashboard/reorder'
    | '/dashboard/testimonials'
    | '/admin/'
    | '/dashboard/'
    | '/_authenticated/p/$tenantSlug'
    | '/dashboard/customers/$customerId'
    | '/p/$tenantSlug/join'
    | '/_authenticated/p/$tenantSlug/complete'
    | '/_authenticated/p/$tenantSlug/guide'
    | '/_authenticated/p/$tenantSlug/journey'
    | '/_authenticated/p/$tenantSlug/kit'
    | '/_authenticated/p/$tenantSlug/progress'
    | '/_authenticated/p/$tenantSlug/today'
    | '/admin/content/programs/$programId/days'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PTenantSlugJoinRoute: typeof PTenantSlugJoinRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/at-risk': {
      id: '/dashboard/at-risk'
      path: '/at-risk'
      fullPath: '/dashboard/at-risk'
      preLoaderRoute: typeof DashboardAtRiskRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/branding': {
      id: '/dashboard/branding'
      path: '/branding'
      fullPath: '/dashboard/branding'
      preLoaderRoute: typeof DashboardBrandingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/customers': {
      id: '/dashboard/customers'
      path: '/customers'
      fullPath: '/dashboard/customers'
      preLoaderRoute: typeof DashboardCustomersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/invite': {
      id: '/dashboard/invite'
      path: '/invite'
      fullPath: '/dashboard/invite'
      preLoaderRoute: typeof DashboardInviteRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reorder': {
      id: '/dashboard/reorder'
      path: '/reorder'
      fullPath: '/dashboard/reorder'
      preLoaderRoute: typeof DashboardReorderRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/testimonials': {
      id: '/dashboard/testimonials'
      path: '/testimonials'
      fullPath: '/dashboard/testimonials'
      preLoaderRoute: typeof DashboardTestimonialsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_authenticated/p/$tenantSlug': {
      id: '/_authenticated/p/$tenantSlug'
      path: '/p/$tenantSlug'
      fullPath: '/p/$tenantSlug'
      preLoaderRoute: typeof AuthenticatedPTenantSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/dashboard/customers/$customerId': {
      id: '/dashboard/customers/$customerId'
      path: '/$customerId'
      fullPath: '/dashboard/customers/$customerId'
      preLoaderRoute: typeof DashboardCustomersCustomerIdRouteImport
      parentRoute: typeof DashboardCustomersRoute
    }
    '/p/$tenantSlug/join': {
      id: '/p/$tenantSlug/join'
      path: '/p/$tenantSlug/join'
      fullPath: '/p/$tenantSlug/join'
      preLoaderRoute: typeof PTenantSlugJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/p/$tenantSlug/complete': {
      id: '/_authenticated/p/$tenantSlug/complete'
      path: '/complete'
      fullPath: '/p/$tenantSlug/complete'
      preLoaderRoute: typeof AuthenticatedPTenantSlugCompleteRouteImport
      parentRoute: typeof AuthenticatedPTenantSlugRoute
    }
    '/_authenticated/p/$tenantSlug/guide': {
      id: '/_authenticated/p/$tenantSlug/guide'
      path: '/guide'
      fullPath: '/p/$tenantSlug/guide'
      preLoaderRoute: typeof AuthenticatedPTenantSlugGuideRouteImport
      parentRoute: typeof AuthenticatedPTenantSlugRoute
    }
    '/_authenticated/p/$tenantSlug/journey': {
      id: '/_authenticated/p/$tenantSlug/journey'
      path: '/journey'
      fullPath: '/p/$tenantSlug/journey'
      preLoaderRoute: typeof AuthenticatedPTenantSlugJourneyRouteImport
      parentRoute: typeof AuthenticatedPTenantSlugRoute
    }
    '/_authenticated/p/$tenantSlug/kit': {
      id: '/_authenticated/p/$tenantSlug/kit'
      path: '/kit'
      fullPath: '/p/$tenantSlug/kit'
      preLoaderRoute: typeof AuthenticatedPTenantSlugKitRouteImport
      parentRoute: typeof AuthenticatedPTenantSlugRoute
    }
    '/_authenticated/p/$tenantSlug/progress': {
      id: '/_authenticated/p/$tenantSlug/progress'
      path: '/progress'
      fullPath: '/p/$tenantSlug/progress'
      preLoaderRoute: typeof AuthenticatedPTenantSlugProgressRouteImport
      parentRoute: typeof AuthenticatedPTenantSlugRoute
    }
    '/_authenticated/p/$tenantSlug/today': {
      id: '/_authenticated/p/$tenantSlug/today'
      path: '/today'
      fullPath: '/p/$tenantSlug/today'
      preLoaderRoute: typeof AuthenticatedPTenantSlugTodayRouteImport
      parentRoute: typeof AuthenticatedPTenantSlugRoute
    }
    '/admin/content/programs/$programId/days': {
      id: '/admin/content/programs/$programId/days'
      path: '/programs/$programId/days'
      fullPath: '/admin/content/programs/$programId/days'
      preLoaderRoute: typeof AdminContentProgramsProgramIdDaysRouteImport
      parentRoute: typeof AdminContentRoute
    }
  }
}

interface AuthenticatedPTenantSlugRouteChildren {
  AuthenticatedPTenantSlugCompleteRoute: typeof AuthenticatedPTenantSlugCompleteRoute
  AuthenticatedPTenantSlugGuideRoute: typeof AuthenticatedPTenantSlugGuideRoute
  AuthenticatedPTenantSlugJourneyRoute: typeof AuthenticatedPTenantSlugJourneyRoute
  AuthenticatedPTenantSlugKitRoute: typeof AuthenticatedPTenantSlugKitRoute
  AuthenticatedPTenantSlugProgressRoute: typeof AuthenticatedPTenantSlugProgressRoute
  AuthenticatedPTenantSlugTodayRoute: typeof AuthenticatedPTenantSlugTodayRoute
}

const AuthenticatedPTenantSlugRouteChildren: AuthenticatedPTenantSlugRouteChildren =
  {
    AuthenticatedPTenantSlugCompleteRoute:
      AuthenticatedPTenantSlugCompleteRoute,
    AuthenticatedPTenantSlugGuideRoute: AuthenticatedPTenantSlugGuideRoute,
    AuthenticatedPTenantSlugJourneyRoute: AuthenticatedPTenantSlugJourneyRoute,
    AuthenticatedPTenantSlugKitRoute: AuthenticatedPTenantSlugKitRoute,
    AuthenticatedPTenantSlugProgressRoute:
      AuthenticatedPTenantSlugProgressRoute,
    AuthenticatedPTenantSlugTodayRoute: AuthenticatedPTenantSlugTodayRoute,
  }

const AuthenticatedPTenantSlugRouteWithChildren =
  AuthenticatedPTenantSlugRoute._addFileChildren(
    AuthenticatedPTenantSlugRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedPTenantSlugRoute: typeof AuthenticatedPTenantSlugRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedPTenantSlugRoute: AuthenticatedPTenantSlugRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AdminContentRouteChildren {
  AdminContentProgramsProgramIdDaysRoute: typeof AdminContentProgramsProgramIdDaysRoute
}

const AdminContentRouteChildren: AdminContentRouteChildren = {
  AdminContentProgramsProgramIdDaysRoute:
    AdminContentProgramsProgramIdDaysRoute,
}

const AdminContentRouteWithChildren = AdminContentRoute._addFileChildren(
  AdminContentRouteChildren,
)

interface AdminRouteChildren {
  AdminContentRoute: typeof AdminContentRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminContentRoute: AdminContentRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardCustomersRouteChildren {
  DashboardCustomersCustomerIdRoute: typeof DashboardCustomersCustomerIdRoute
}

const DashboardCustomersRouteChildren: DashboardCustomersRouteChildren = {
  DashboardCustomersCustomerIdRoute: DashboardCustomersCustomerIdRoute,
}

const DashboardCustomersRouteWithChildren =
  DashboardCustomersRoute._addFileChildren(DashboardCustomersRouteChildren)

interface DashboardRouteChildren {
  DashboardAtRiskRoute: typeof DashboardAtRiskRoute
  DashboardBrandingRoute: typeof DashboardBrandingRoute
  DashboardCustomersRoute: typeof DashboardCustomersRouteWithChildren
  DashboardInviteRoute: typeof DashboardInviteRoute
  DashboardReorderRoute: typeof DashboardReorderRoute
  DashboardTestimonialsRoute: typeof DashboardTestimonialsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAtRiskRoute: DashboardAtRiskRoute,
  DashboardBrandingRoute: DashboardBrandingRoute,
  DashboardCustomersRoute: DashboardCustomersRouteWithChildren,
  DashboardInviteRoute: DashboardInviteRoute,
  DashboardReorderRoute: DashboardReorderRoute,
  DashboardTestimonialsRoute: DashboardTestimonialsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PTenantSlugJoinRoute: PTenantSlugJoinRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
