/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MedicalDisclaimerRouteImport } from './routes/medical-disclaimer'
import { Route as MovementRouteImport } from './routes/movement'
import { Route as NutritionRouteImport } from './routes/nutrition'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProgramRouteImport } from './routes/program'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAccessCodesRouteImport } from './routes/admin/access-codes'
import { Route as AdminKnowledgeRouteImport } from './routes/admin/knowledge'
import { Route as AdminMediaRouteImport } from './routes/admin/media'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminProgramsRouteImport } from './routes/admin/programs'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminTipsRouteImport } from './routes/admin/tips'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAccessRouteImport } from './routes/dashboard/access'
import { Route as DashboardAtRiskRouteImport } from './routes/dashboard/at-risk'
import { Route as DashboardBrandingRouteImport } from './routes/dashboard/branding'
import { Route as DashboardInviteRouteImport } from './routes/dashboard/invite'
import { Route as DashboardLeadsRouteImport } from './routes/dashboard/leads'
import { Route as DashboardPlansRouteImport } from './routes/dashboard/plans'
import { Route as DashboardProductsRouteImport } from './routes/dashboard/products'
import { Route as DashboardReorderRouteImport } from './routes/dashboard/reorder'
import { Route as DashboardTestimonialsRouteImport } from './routes/dashboard/testimonials'
import { Route as AuthenticatedPTenantSlugRouteImport } from './routes/_authenticated/p.$tenantSlug'
import { Route as AdminContentIndexRouteImport } from './routes/admin/content.index'
import { Route as AdminTenantsIndexRouteImport } from './routes/admin/tenants.index'
import { Route as AdminTenantsTenantIdRouteImport } from './routes/admin/tenants.$tenantId'
import { Route as ApiManifestJsonRouteImport } from './routes/api/manifest.json'
import { Route as DashboardCustomersIndexRouteImport } from './routes/dashboard/customers.index'
import { Route as DashboardCustomersCustomerIdRouteImport } from './routes/dashboard/customers.$customerId'
import { Route as AuthenticatedPTenantSlugCompleteRouteImport } from './routes/_authenticated/p.$tenantSlug.complete'
import { Route as AuthenticatedPTenantSlugDietRouteImport } from './routes/_authenticated/p.$tenantSlug.diet'
import { Route as AuthenticatedPTenantSlugGuideRouteImport } from './routes/_authenticated/p.$tenantSlug.guide'
import { Route as AuthenticatedPTenantSlugJourneyRouteImport } from './routes/_authenticated/p.$tenantSlug.journey'
import { Route as AuthenticatedPTenantSlugKitRouteImport } from './routes/_authenticated/p.$tenantSlug.kit'
import { Route as AuthenticatedPTenantSlugProfileRouteImport } from './routes/_authenticated/p.$tenantSlug.profile'
import { Route as AuthenticatedPTenantSlugProgressRouteImport } from './routes/_authenticated/p.$tenantSlug.progress'
import { Route as AuthenticatedPTenantSlugTodayRouteImport } from './routes/_authenticated/p.$tenantSlug.today'
import { Route as AdminContentProgramsProgramIdDaysRouteImport } from './routes/admin/content/programs/$programId/days'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalDisclaimerRoute = MedicalDisclaimerRouteImport.update({
  id: '/medical-disclaimer',
  path: '/medical-disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const MovementRoute = MovementRouteImport.update({
  id: '/movement',
  path: '/movement',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionRoute = NutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramRoute = ProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccessCodesRoute = AdminAccessCodesRouteImport.update({
  id: '/access-codes',
  path: '/access-codes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKnowledgeRoute = AdminKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProgramsRoute = AdminProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTipsRoute = AdminTipsRouteImport.update({
  id: '/tips',
  path: '/tips',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccessRoute = DashboardAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAtRiskRoute = DashboardAtRiskRouteImport.update({
  id: '/at-risk',
  path: '/at-risk',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBrandingRoute = DashboardBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInviteRoute = DashboardInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeadsRoute = DashboardLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlansRoute = DashboardPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProductsRoute = DashboardProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReorderRoute = DashboardReorderRouteImport.update({
  id: '/reorder',
  path: '/reorder',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTestimonialsRoute = DashboardTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthenticatedPTenantSlugRoute =
  AuthenticatedPTenantSlugRouteImport.update({
    id: '/p/$tenantSlug',
    path: '/p/$tenantSlug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AdminContentIndexRoute = AdminContentIndexRouteImport.update({
  id: '/content/',
  path: '/content/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTenantsIndexRoute = AdminTenantsIndexRouteImport.update({
  id: '/tenants/',
  path: '/tenants/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTenantsTenantIdRoute = AdminTenantsTenantIdRouteImport.update({
  id: '/tenants/$tenantId',
  path: '/tenants/$tenantId',
  getParentRoute: () => AdminRoute,
} as any)
const ApiManifestJsonRoute = ApiManifestJsonRouteImport.update({
  id: '/api/manifest/json',
  path: '/api/manifest/json',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCustomersIndexRoute = DashboardCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCustomersCustomerIdRoute =
  DashboardCustomersCustomerIdRouteImport.update({
    id: '/customers/$customerId',
    path: '/customers/$customerId',
    getParentRoute: () => DashboardRoute,
  } as any)
const AuthenticatedPTenantSlugCompleteRoute =
  AuthenticatedPTenantSlugCompleteRouteImport.update({
    id: '/complete',
    path: '/complete',
    getParentRoute: () => AuthenticatedPTenantSlugRoute,
  } as any)
const AuthenticatedPTenantSlugDietRoute =
  AuthenticatedPTenantSlugDietRouteImport.update({
    id: '/diet',
    path: '/diet',
    getParentRoute: () => AuthenticatedPTenantSlugRoute,
  } as any)
const AuthenticatedPTenantSlugGuideRoute =
  AuthenticatedPTenantSlugGuideRouteImport.update({
    id: '/guide',
    path: '/guide',
    getParentRoute: () => AuthenticatedPTenantSlugRoute,
  } as any)
const AuthenticatedPTenantSlugJourneyRoute =
  AuthenticatedPTenantSlugJourneyRouteImport.update({
    id: '/journey',
    path: '/journey',
    getParentRoute: () => AuthenticatedPTenantSlugRoute,
  } as any)
const AuthenticatedPTenantSlugKitRoute =
  AuthenticatedPTenantSlugKitRouteImport.update({
    id: '/kit',
    path: '/kit',
    getParentRoute: () => AuthenticatedPTenantSlugRoute,
  } as any)
const AuthenticatedPTenantSlugProfileRoute =
  AuthenticatedPTenantSlugProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedPTenantSlugRoute,
  } as any)
const AuthenticatedPTenantSlugProgressRoute =
  AuthenticatedPTenantSlugProgressRouteImport.update({
    id: '/progress',
    path: '/progress',
    getParentRoute: () => AuthenticatedPTenantSlugRoute,
  } as any)
const AuthenticatedPTenantSlugTodayRoute =
  AuthenticatedPTenantSlugTodayRouteImport.update({
    id: '/today',
    path: '/today',
    getParentRoute: () => AuthenticatedPTenantSlugRoute,
  } as any)
const AdminContentProgramsProgramIdDaysRoute =
  AdminContentProgramsProgramIdDaysRouteImport.update({
    id: '/content/programs/$programId/days',
    path: '/content/programs/$programId/days',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/coach': typeof CoachRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/medical-disclaimer': typeof MedicalDisclaimerRoute
  '/movement': typeof MovementRoute
  '/nutrition': typeof NutritionRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/program': typeof ProgramRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/admin/access-codes': typeof AdminAccessCodesRoute
  '/admin/knowledge': typeof AdminKnowledgeRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tips': typeof AdminTipsRoute
  '/dashboard/access': typeof DashboardAccessRoute
  '/dashboard/at-risk': typeof DashboardAtRiskRoute
  '/dashboard/branding': typeof DashboardBrandingRoute
  '/dashboard/invite': typeof DashboardInviteRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/plans': typeof DashboardPlansRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/reorder': typeof DashboardReorderRoute
  '/dashboard/testimonials': typeof DashboardTestimonialsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/p/$tenantSlug': typeof AuthenticatedPTenantSlugRouteWithChildren
  '/admin/tenants/$tenantId': typeof AdminTenantsTenantIdRoute
  '/api/manifest/json': typeof ApiManifestJsonRoute
  '/dashboard/customers/$customerId': typeof DashboardCustomersCustomerIdRoute
  '/admin/content/': typeof AdminContentIndexRoute
  '/admin/tenants/': typeof AdminTenantsIndexRoute
  '/dashboard/customers/': typeof DashboardCustomersIndexRoute
  '/p/$tenantSlug/complete': typeof AuthenticatedPTenantSlugCompleteRoute
  '/p/$tenantSlug/diet': typeof AuthenticatedPTenantSlugDietRoute
  '/p/$tenantSlug/guide': typeof AuthenticatedPTenantSlugGuideRoute
  '/p/$tenantSlug/journey': typeof AuthenticatedPTenantSlugJourneyRoute
  '/p/$tenantSlug/kit': typeof AuthenticatedPTenantSlugKitRoute
  '/p/$tenantSlug/profile': typeof AuthenticatedPTenantSlugProfileRoute
  '/p/$tenantSlug/progress': typeof AuthenticatedPTenantSlugProgressRoute
  '/p/$tenantSlug/today': typeof AuthenticatedPTenantSlugTodayRoute
  '/admin/content/programs/$programId/days': typeof AdminContentProgramsProgramIdDaysRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coach': typeof CoachRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/medical-disclaimer': typeof MedicalDisclaimerRoute
  '/movement': typeof MovementRoute
  '/nutrition': typeof NutritionRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/program': typeof ProgramRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/admin/access-codes': typeof AdminAccessCodesRoute
  '/admin/knowledge': typeof AdminKnowledgeRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tips': typeof AdminTipsRoute
  '/dashboard/access': typeof DashboardAccessRoute
  '/dashboard/at-risk': typeof DashboardAtRiskRoute
  '/dashboard/branding': typeof DashboardBrandingRoute
  '/dashboard/invite': typeof DashboardInviteRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/plans': typeof DashboardPlansRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/reorder': typeof DashboardReorderRoute
  '/dashboard/testimonials': typeof DashboardTestimonialsRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/p/$tenantSlug': typeof AuthenticatedPTenantSlugRouteWithChildren
  '/admin/tenants/$tenantId': typeof AdminTenantsTenantIdRoute
  '/api/manifest/json': typeof ApiManifestJsonRoute
  '/dashboard/customers/$customerId': typeof DashboardCustomersCustomerIdRoute
  '/admin/content': typeof AdminContentIndexRoute
  '/admin/tenants': typeof AdminTenantsIndexRoute
  '/dashboard/customers': typeof DashboardCustomersIndexRoute
  '/p/$tenantSlug/complete': typeof AuthenticatedPTenantSlugCompleteRoute
  '/p/$tenantSlug/diet': typeof AuthenticatedPTenantSlugDietRoute
  '/p/$tenantSlug/guide': typeof AuthenticatedPTenantSlugGuideRoute
  '/p/$tenantSlug/journey': typeof AuthenticatedPTenantSlugJourneyRoute
  '/p/$tenantSlug/kit': typeof AuthenticatedPTenantSlugKitRoute
  '/p/$tenantSlug/profile': typeof AuthenticatedPTenantSlugProfileRoute
  '/p/$tenantSlug/progress': typeof AuthenticatedPTenantSlugProgressRoute
  '/p/$tenantSlug/today': typeof AuthenticatedPTenantSlugTodayRoute
  '/admin/content/programs/$programId/days': typeof AdminContentProgramsProgramIdDaysRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/coach': typeof CoachRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/medical-disclaimer': typeof MedicalDisclaimerRoute
  '/movement': typeof MovementRoute
  '/nutrition': typeof NutritionRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/program': typeof ProgramRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/admin/access-codes': typeof AdminAccessCodesRoute
  '/admin/knowledge': typeof AdminKnowledgeRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tips': typeof AdminTipsRoute
  '/dashboard/access': typeof DashboardAccessRoute
  '/dashboard/at-risk': typeof DashboardAtRiskRoute
  '/dashboard/branding': typeof DashboardBrandingRoute
  '/dashboard/invite': typeof DashboardInviteRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/plans': typeof DashboardPlansRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/reorder': typeof DashboardReorderRoute
  '/dashboard/testimonials': typeof DashboardTestimonialsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/_authenticated/p/$tenantSlug': typeof AuthenticatedPTenantSlugRouteWithChildren
  '/admin/tenants/$tenantId': typeof AdminTenantsTenantIdRoute
  '/api/manifest/json': typeof ApiManifestJsonRoute
  '/dashboard/customers/$customerId': typeof DashboardCustomersCustomerIdRoute
  '/admin/content/': typeof AdminContentIndexRoute
  '/admin/tenants/': typeof AdminTenantsIndexRoute
  '/dashboard/customers/': typeof DashboardCustomersIndexRoute
  '/_authenticated/p/$tenantSlug/complete': typeof AuthenticatedPTenantSlugCompleteRoute
  '/_authenticated/p/$tenantSlug/diet': typeof AuthenticatedPTenantSlugDietRoute
  '/_authenticated/p/$tenantSlug/guide': typeof AuthenticatedPTenantSlugGuideRoute
  '/_authenticated/p/$tenantSlug/journey': typeof AuthenticatedPTenantSlugJourneyRoute
  '/_authenticated/p/$tenantSlug/kit': typeof AuthenticatedPTenantSlugKitRoute
  '/_authenticated/p/$tenantSlug/profile': typeof AuthenticatedPTenantSlugProfileRoute
  '/_authenticated/p/$tenantSlug/progress': typeof AuthenticatedPTenantSlugProgressRoute
  '/_authenticated/p/$tenantSlug/today': typeof AuthenticatedPTenantSlugTodayRoute
  '/admin/content/programs/$programId/days': typeof AdminContentProgramsProgramIdDaysRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/coach'
    | '/dashboard'
    | '/faq'
    | '/how-it-works'
    | '/login'
    | '/medical-disclaimer'
    | '/movement'
    | '/nutrition'
    | '/onboarding'
    | '/privacy'
    | '/program'
    | '/signup'
    | '/terms'
    | '/admin/access-codes'
    | '/admin/knowledge'
    | '/admin/media'
    | '/admin/products'
    | '/admin/programs'
    | '/admin/settings'
    | '/admin/tips'
    | '/dashboard/access'
    | '/dashboard/at-risk'
    | '/dashboard/branding'
    | '/dashboard/invite'
    | '/dashboard/leads'
    | '/dashboard/plans'
    | '/dashboard/products'
    | '/dashboard/reorder'
    | '/dashboard/testimonials'
    | '/admin/'
    | '/dashboard/'
    | '/p/$tenantSlug'
    | '/admin/tenants/$tenantId'
    | '/api/manifest/json'
    | '/dashboard/customers/$customerId'
    | '/admin/content/'
    | '/admin/tenants/'
    | '/dashboard/customers/'
    | '/p/$tenantSlug/complete'
    | '/p/$tenantSlug/diet'
    | '/p/$tenantSlug/guide'
    | '/p/$tenantSlug/journey'
    | '/p/$tenantSlug/kit'
    | '/p/$tenantSlug/profile'
    | '/p/$tenantSlug/progress'
    | '/p/$tenantSlug/today'
    | '/admin/content/programs/$programId/days'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coach'
    | '/faq'
    | '/how-it-works'
    | '/login'
    | '/medical-disclaimer'
    | '/movement'
    | '/nutrition'
    | '/onboarding'
    | '/privacy'
    | '/program'
    | '/signup'
    | '/terms'
    | '/admin/access-codes'
    | '/admin/knowledge'
    | '/admin/media'
    | '/admin/products'
    | '/admin/programs'
    | '/admin/settings'
    | '/admin/tips'
    | '/dashboard/access'
    | '/dashboard/at-risk'
    | '/dashboard/branding'
    | '/dashboard/invite'
    | '/dashboard/leads'
    | '/dashboard/plans'
    | '/dashboard/products'
    | '/dashboard/reorder'
    | '/dashboard/testimonials'
    | '/admin'
    | '/dashboard'
    | '/p/$tenantSlug'
    | '/admin/tenants/$tenantId'
    | '/api/manifest/json'
    | '/dashboard/customers/$customerId'
    | '/admin/content'
    | '/admin/tenants'
    | '/dashboard/customers'
    | '/p/$tenantSlug/complete'
    | '/p/$tenantSlug/diet'
    | '/p/$tenantSlug/guide'
    | '/p/$tenantSlug/journey'
    | '/p/$tenantSlug/kit'
    | '/p/$tenantSlug/profile'
    | '/p/$tenantSlug/progress'
    | '/p/$tenantSlug/today'
    | '/admin/content/programs/$programId/days'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/coach'
    | '/dashboard'
    | '/faq'
    | '/how-it-works'
    | '/login'
    | '/medical-disclaimer'
    | '/movement'
    | '/nutrition'
    | '/onboarding'
    | '/privacy'
    | '/program'
    | '/signup'
    | '/terms'
    | '/admin/access-codes'
    | '/admin/knowledge'
    | '/admin/media'
    | '/admin/products'
    | '/admin/programs'
    | '/admin/settings'
    | '/admin/tips'
    | '/dashboard/access'
    | '/dashboard/at-risk'
    | '/dashboard/branding'
    | '/dashboard/invite'
    | '/dashboard/leads'
    | '/dashboard/plans'
    | '/dashboard/products'
    | '/dashboard/reorder'
    | '/dashboard/testimonials'
    | '/admin/'
    | '/dashboard/'
    | '/_authenticated/p/$tenantSlug'
    | '/admin/tenants/$tenantId'
    | '/api/manifest/json'
    | '/dashboard/customers/$customerId'
    | '/admin/content/'
    | '/admin/tenants/'
    | '/dashboard/customers/'
    | '/_authenticated/p/$tenantSlug/complete'
    | '/_authenticated/p/$tenantSlug/diet'
    | '/_authenticated/p/$tenantSlug/guide'
    | '/_authenticated/p/$tenantSlug/journey'
    | '/_authenticated/p/$tenantSlug/kit'
    | '/_authenticated/p/$tenantSlug/profile'
    | '/_authenticated/p/$tenantSlug/progress'
    | '/_authenticated/p/$tenantSlug/today'
    | '/admin/content/programs/$programId/days'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  CoachRoute: typeof CoachRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FaqRoute: typeof FaqRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  MedicalDisclaimerRoute: typeof MedicalDisclaimerRoute
  MovementRoute: typeof MovementRoute
  NutritionRoute: typeof NutritionRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProgramRoute: typeof ProgramRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  ApiManifestJsonRoute: typeof ApiManifestJsonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-disclaimer': {
      id: '/medical-disclaimer'
      path: '/medical-disclaimer'
      fullPath: '/medical-disclaimer'
      preLoaderRoute: typeof MedicalDisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movement': {
      id: '/movement'
      path: '/movement'
      fullPath: '/movement'
      preLoaderRoute: typeof MovementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition': {
      id: '/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof NutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program': {
      id: '/program'
      path: '/program'
      fullPath: '/program'
      preLoaderRoute: typeof ProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/access-codes': {
      id: '/admin/access-codes'
      path: '/access-codes'
      fullPath: '/admin/access-codes'
      preLoaderRoute: typeof AdminAccessCodesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/knowledge': {
      id: '/admin/knowledge'
      path: '/knowledge'
      fullPath: '/admin/knowledge'
      preLoaderRoute: typeof AdminKnowledgeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/programs': {
      id: '/admin/programs'
      path: '/programs'
      fullPath: '/admin/programs'
      preLoaderRoute: typeof AdminProgramsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tips': {
      id: '/admin/tips'
      path: '/tips'
      fullPath: '/admin/tips'
      preLoaderRoute: typeof AdminTipsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/access': {
      id: '/dashboard/access'
      path: '/access'
      fullPath: '/dashboard/access'
      preLoaderRoute: typeof DashboardAccessRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/at-risk': {
      id: '/dashboard/at-risk'
      path: '/at-risk'
      fullPath: '/dashboard/at-risk'
      preLoaderRoute: typeof DashboardAtRiskRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/branding': {
      id: '/dashboard/branding'
      path: '/branding'
      fullPath: '/dashboard/branding'
      preLoaderRoute: typeof DashboardBrandingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/invite': {
      id: '/dashboard/invite'
      path: '/invite'
      fullPath: '/dashboard/invite'
      preLoaderRoute: typeof DashboardInviteRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/leads': {
      id: '/dashboard/leads'
      path: '/leads'
      fullPath: '/dashboard/leads'
      preLoaderRoute: typeof DashboardLeadsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/plans': {
      id: '/dashboard/plans'
      path: '/plans'
      fullPath: '/dashboard/plans'
      preLoaderRoute: typeof DashboardPlansRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products': {
      id: '/dashboard/products'
      path: '/products'
      fullPath: '/dashboard/products'
      preLoaderRoute: typeof DashboardProductsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reorder': {
      id: '/dashboard/reorder'
      path: '/reorder'
      fullPath: '/dashboard/reorder'
      preLoaderRoute: typeof DashboardReorderRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/testimonials': {
      id: '/dashboard/testimonials'
      path: '/testimonials'
      fullPath: '/dashboard/testimonials'
      preLoaderRoute: typeof DashboardTestimonialsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_authenticated/p/$tenantSlug': {
      id: '/_authenticated/p/$tenantSlug'
      path: '/p/$tenantSlug'
      fullPath: '/p/$tenantSlug'
      preLoaderRoute: typeof AuthenticatedPTenantSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/admin/content/': {
      id: '/admin/content/'
      path: '/content'
      fullPath: '/admin/content/'
      preLoaderRoute: typeof AdminContentIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tenants/': {
      id: '/admin/tenants/'
      path: '/tenants'
      fullPath: '/admin/tenants/'
      preLoaderRoute: typeof AdminTenantsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tenants/$tenantId': {
      id: '/admin/tenants/$tenantId'
      path: '/tenants/$tenantId'
      fullPath: '/admin/tenants/$tenantId'
      preLoaderRoute: typeof AdminTenantsTenantIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/manifest/json': {
      id: '/api/manifest/json'
      path: '/api/manifest/json'
      fullPath: '/api/manifest/json'
      preLoaderRoute: typeof ApiManifestJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/customers/': {
      id: '/dashboard/customers/'
      path: '/customers'
      fullPath: '/dashboard/customers/'
      preLoaderRoute: typeof DashboardCustomersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/customers/$customerId': {
      id: '/dashboard/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/dashboard/customers/$customerId'
      preLoaderRoute: typeof DashboardCustomersCustomerIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_authenticated/p/$tenantSlug/complete': {
      id: '/_authenticated/p/$tenantSlug/complete'
      path: '/complete'
      fullPath: '/p/$tenantSlug/complete'
      preLoaderRoute: typeof AuthenticatedPTenantSlugCompleteRouteImport
      parentRoute: typeof AuthenticatedPTenantSlugRoute
    }
    '/_authenticated/p/$tenantSlug/diet': {
      id: '/_authenticated/p/$tenantSlug/diet'
      path: '/diet'
      fullPath: '/p/$tenantSlug/diet'
      preLoaderRoute: typeof AuthenticatedPTenantSlugDietRouteImport
      parentRoute: typeof AuthenticatedPTenantSlugRoute
    }
    '/_authenticated/p/$tenantSlug/guide': {
      id: '/_authenticated/p/$tenantSlug/guide'
      path: '/guide'
      fullPath: '/p/$tenantSlug/guide'
      preLoaderRoute: typeof AuthenticatedPTenantSlugGuideRouteImport
      parentRoute: typeof AuthenticatedPTenantSlugRoute
    }
    '/_authenticated/p/$tenantSlug/journey': {
      id: '/_authenticated/p/$tenantSlug/journey'
      path: '/journey'
      fullPath: '/p/$tenantSlug/journey'
      preLoaderRoute: typeof AuthenticatedPTenantSlugJourneyRouteImport
      parentRoute: typeof AuthenticatedPTenantSlugRoute
    }
    '/_authenticated/p/$tenantSlug/kit': {
      id: '/_authenticated/p/$tenantSlug/kit'
      path: '/kit'
      fullPath: '/p/$tenantSlug/kit'
      preLoaderRoute: typeof AuthenticatedPTenantSlugKitRouteImport
      parentRoute: typeof AuthenticatedPTenantSlugRoute
    }
    '/_authenticated/p/$tenantSlug/profile': {
      id: '/_authenticated/p/$tenantSlug/profile'
      path: '/profile'
      fullPath: '/p/$tenantSlug/profile'
      preLoaderRoute: typeof AuthenticatedPTenantSlugProfileRouteImport
      parentRoute: typeof AuthenticatedPTenantSlugRoute
    }
    '/_authenticated/p/$tenantSlug/progress': {
      id: '/_authenticated/p/$tenantSlug/progress'
      path: '/progress'
      fullPath: '/p/$tenantSlug/progress'
      preLoaderRoute: typeof AuthenticatedPTenantSlugProgressRouteImport
      parentRoute: typeof AuthenticatedPTenantSlugRoute
    }
    '/_authenticated/p/$tenantSlug/today': {
      id: '/_authenticated/p/$tenantSlug/today'
      path: '/today'
      fullPath: '/p/$tenantSlug/today'
      preLoaderRoute: typeof AuthenticatedPTenantSlugTodayRouteImport
      parentRoute: typeof AuthenticatedPTenantSlugRoute
    }
    '/admin/content/programs/$programId/days': {
      id: '/admin/content/programs/$programId/days'
      path: '/content/programs/$programId/days'
      fullPath: '/admin/content/programs/$programId/days'
      preLoaderRoute: typeof AdminContentProgramsProgramIdDaysRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AuthenticatedPTenantSlugRouteChildren {
  AuthenticatedPTenantSlugCompleteRoute: typeof AuthenticatedPTenantSlugCompleteRoute
  AuthenticatedPTenantSlugDietRoute: typeof AuthenticatedPTenantSlugDietRoute
  AuthenticatedPTenantSlugGuideRoute: typeof AuthenticatedPTenantSlugGuideRoute
  AuthenticatedPTenantSlugJourneyRoute: typeof AuthenticatedPTenantSlugJourneyRoute
  AuthenticatedPTenantSlugKitRoute: typeof AuthenticatedPTenantSlugKitRoute
  AuthenticatedPTenantSlugProfileRoute: typeof AuthenticatedPTenantSlugProfileRoute
  AuthenticatedPTenantSlugProgressRoute: typeof AuthenticatedPTenantSlugProgressRoute
  AuthenticatedPTenantSlugTodayRoute: typeof AuthenticatedPTenantSlugTodayRoute
}

const AuthenticatedPTenantSlugRouteChildren: AuthenticatedPTenantSlugRouteChildren =
  {
    AuthenticatedPTenantSlugCompleteRoute:
      AuthenticatedPTenantSlugCompleteRoute,
    AuthenticatedPTenantSlugDietRoute: AuthenticatedPTenantSlugDietRoute,
    AuthenticatedPTenantSlugGuideRoute: AuthenticatedPTenantSlugGuideRoute,
    AuthenticatedPTenantSlugJourneyRoute: AuthenticatedPTenantSlugJourneyRoute,
    AuthenticatedPTenantSlugKitRoute: AuthenticatedPTenantSlugKitRoute,
    AuthenticatedPTenantSlugProfileRoute: AuthenticatedPTenantSlugProfileRoute,
    AuthenticatedPTenantSlugProgressRoute:
      AuthenticatedPTenantSlugProgressRoute,
    AuthenticatedPTenantSlugTodayRoute: AuthenticatedPTenantSlugTodayRoute,
  }

const AuthenticatedPTenantSlugRouteWithChildren =
  AuthenticatedPTenantSlugRoute._addFileChildren(
    AuthenticatedPTenantSlugRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedPTenantSlugRoute: typeof AuthenticatedPTenantSlugRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedPTenantSlugRoute: AuthenticatedPTenantSlugRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AdminRouteChildren {
  AdminAccessCodesRoute: typeof AdminAccessCodesRoute
  AdminKnowledgeRoute: typeof AdminKnowledgeRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminProgramsRoute: typeof AdminProgramsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTipsRoute: typeof AdminTipsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminTenantsTenantIdRoute: typeof AdminTenantsTenantIdRoute
  AdminContentIndexRoute: typeof AdminContentIndexRoute
  AdminTenantsIndexRoute: typeof AdminTenantsIndexRoute
  AdminContentProgramsProgramIdDaysRoute: typeof AdminContentProgramsProgramIdDaysRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccessCodesRoute: AdminAccessCodesRoute,
  AdminKnowledgeRoute: AdminKnowledgeRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminProgramsRoute: AdminProgramsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTipsRoute: AdminTipsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminTenantsTenantIdRoute: AdminTenantsTenantIdRoute,
  AdminContentIndexRoute: AdminContentIndexRoute,
  AdminTenantsIndexRoute: AdminTenantsIndexRoute,
  AdminContentProgramsProgramIdDaysRoute:
    AdminContentProgramsProgramIdDaysRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardAccessRoute: typeof DashboardAccessRoute
  DashboardAtRiskRoute: typeof DashboardAtRiskRoute
  DashboardBrandingRoute: typeof DashboardBrandingRoute
  DashboardInviteRoute: typeof DashboardInviteRoute
  DashboardLeadsRoute: typeof DashboardLeadsRoute
  DashboardPlansRoute: typeof DashboardPlansRoute
  DashboardProductsRoute: typeof DashboardProductsRoute
  DashboardReorderRoute: typeof DashboardReorderRoute
  DashboardTestimonialsRoute: typeof DashboardTestimonialsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCustomersCustomerIdRoute: typeof DashboardCustomersCustomerIdRoute
  DashboardCustomersIndexRoute: typeof DashboardCustomersIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccessRoute: DashboardAccessRoute,
  DashboardAtRiskRoute: DashboardAtRiskRoute,
  DashboardBrandingRoute: DashboardBrandingRoute,
  DashboardInviteRoute: DashboardInviteRoute,
  DashboardLeadsRoute: DashboardLeadsRoute,
  DashboardPlansRoute: DashboardPlansRoute,
  DashboardProductsRoute: DashboardProductsRoute,
  DashboardReorderRoute: DashboardReorderRoute,
  DashboardTestimonialsRoute: DashboardTestimonialsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCustomersCustomerIdRoute: DashboardCustomersCustomerIdRoute,
  DashboardCustomersIndexRoute: DashboardCustomersIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  CoachRoute: CoachRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FaqRoute: FaqRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  MedicalDisclaimerRoute: MedicalDisclaimerRoute,
  MovementRoute: MovementRoute,
  NutritionRoute: NutritionRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  ProgramRoute: ProgramRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  ApiManifestJsonRoute: ApiManifestJsonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
