// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dvpjwedhshjrgjkpjrlj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR2cGp3ZWRoc2hqcmdqa3BqcmxqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODYyOTAyOTUsImV4cCI6MjEwMTg2NjI5NX0.Od7qZit2ipI6sKGpxrUlBTcpUVcbYAr9G02ykYZIfsY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});